server:
  port: 8888

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

zuul:
  routes:
    ts:
      path: /ts/**
      serviceId: service-config-client
  ratelimit:
    enabled: true
    default-policy:
      limit: 1
      quota: 2
      refresh-interval: 3
  #以上配置表示启用限流策略，并且所有服务在3秒内只能有1次请求且所有请求时间总和不得超过2秒