server:
  port: 8005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/ # 搜索src/main/resource 下的properties文件夹下的文件
  application:
    name: service-config
  profiles:
    active: native # 配置使用本地储存
