server:
  port: 8888

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

zuul:
  routes:
    ts:
      path: /ts/**
      serviceId: service-config-client
  ratelimit:
    enabled: true
    default-policy:
      limit: 1
      quota: 2
      refresh-interval: 3
    #以上配置表示启用限流策略，并且所有服务在3秒内只能有1次请求且所有请求时间总和不得超过2秒
    policies:
      testservice:
        limit: 10
        quota: 50
        refresh-interval: 60
        type: url
    #以上配置单独为testservice配置了限流策略。60秒内访问次数不得查过10次且访问时间这不得超过50秒。
