server:
  port: 8181
  servlet:
    context-path: /order-system

spring:
  datasource:
    url: jdbc:mysql://172.28.104.18:3306/test_1?autoReconnect=true&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: cmcc1234@

mybatis:
  mapper-locations: classpath:generator/mapping/*.xml
  type-aliases-package: com.zzk.order.entity
  config-location:

logging:
  level:
    root: info